services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Map Redis port to host
    container_name: core-banking-redis
    restart: always
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  core-banking-api:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "9696:9696"
    depends_on:
      - maildev
      - redis
    environment:
      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: ""
      SPRING_MAIL_PASSWORD: ""
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379