services:
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  core-banking-api:
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile (default is Dockerfile)
    ports:
      - "8989:8989"
    depends_on:
      - maildev
    environment:
      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: ""
      SPRING_MAIL_PASSWORD: ""