spring:
  application:
    name: CoreBankingBE-System
  datasource:
    url: jdbc:mysql://localhost:3306/core_bank_be_system
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax.persistence.validation.mode: AUTO
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false
    cache-names: accounts, account, savings_plans
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: false # Disable STARTTLS for MailDev
          auth: false
  kafka:
    listener:
      auto-startup: false
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: core-banking-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.ndifreke.core_banking_api.transaction.events
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 4cb8d78ee951f97ba735898fde76bdf352d03617c4347ef0e6412134841ac694
  expiration: 3600000

server:
  port: 8989

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR